### ISSUE TITLE
pymapd 0.8.1 won't load in Python 3.7.2 on Windows

### ISSUE THREAD

**Issue by realtonyyoung** [omnisci/pymapd#175]
Customer is trying to use pymapd 0.8.1 with Python 3.7.2 on Windows and getting an exception:

```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> self._handle = _dlopen(self._name), mode)
  File "<stdin>", line 1
    self._handle = _dlopen(self._name), mode)
                                            ^
SyntaxError: invalid syntax
>>> from pymapd import connect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pymapd\__init__.py", line 19, in <module>
    from .connection import (  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pymapd\connection.py", line 18, in <module>
    from .cursor import Cursor
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pymapd\cursor.py", line 5, in <module>
    from ._parsers import (_extract_col_vals, _extract_description,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pymapd\_parsers.py", line 14, in <module>
    from .ipc import load_buffer, shmdt
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pymapd\ipc.py", line 9, in <module>
    libc = ctypes.CDLL(libc_so)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

Pymapd version 0.8.1

I'm able to replicate this in my windows environment

However, on Centos 7 it's working just fine: same python version

**Comment by randyzwitch** [comment]
Related: #164 

Thanks for reporting @realtonyyoung. This error occurs because pymapd is looking for some C libraries which pymapd isn't finding. I believe this is occurring because I have Visual Studio installed in my Windows environment (which installs the C/C++ toolchain), but the user doesn't.

So the quick, but unpleasant answer to get started this instant _might be_ to install Visual Studio to get the C/C++ compiler toolchain. In the near term, we'll patch this to have better error handling, possibly as part of fixing #164
