### ISSUE TITLE
ModuleNotFoundError: No module named 'omnisci.mapd'; 'omnisci' is not a package

### ISSUE THREAD

**Issue by BrianLondon** [omnisci/pymapd#293]
I'm having trouble importing pymapd. The import itself is resulting in error. Code to reporduce is simply:

```python
>>> import pymapd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/[username]/.virtualenvs/omnisci-tamr/lib/python3.6/site-packages/pymapd/__init__.py", line 17, in <module>
    from .connection import (  # noqa
  File "/Users/[username]/.virtualenvs/omnisci-tamr/lib/python3.6/site-packages/pymapd/connection.py", line 13, in <module>
    from omnisci.mapd.MapD import Client, TCreateParams
ModuleNotFoundError: No module named 'omnisci.mapd'; 'omnisci' is not a package
```

Environment is MacOS10.4 with pymapd installed via `pip`. Full python environment is:

```
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
```

```
Cython==0.29.15
geojson==2.5.0
llvmlite==0.31.0
netifaces==0.10.9
numba==0.48.0
numpy==1.18.1
packaging==20.1
pandas==1.0.1
ply==3.11
pyarrow==0.13.0
pymapd==0.19.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
rbc-project==0.2.0.dev0
six==1.14.0
SQLAlchemy==1.3.13
tblib==1.6.0
thrift==0.11.0
thriftpy2==0.4.10
``` 

At first I thought this error might be related to https://github.com/omnisci/pymapd/issues/145 but in my case it appears to fail much earlier.

**Comment by randyzwitch** [comment]
Thanks for reporting @BrianLondon, I'll take a look.

**Comment by randyzwitch** [comment]
I still want to dig in a little more, but this might just be an accidental area where we forgot to up our minimum Python to 3.7. It works on OSX with a clean virtualenv:

```python
Randys-MBP:~ randyzwitch$ cd pymapdvenv/
Randys-MBP:pymapdvenv randyzwitch$ cd bin/
Randys-MBP:bin randyzwitch$ source activate
(pymapdvenv) Randys-MBP:bin randyzwitch$ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(pymapdvenv) Randys-MBP:bin randyzwitch$ pip install pymapd
Collecting pymapd
  Using cached pymapd-0.19.0.tar.gz (6.4 MB)
Collecting thrift==0.11.0
  Downloading thrift-0.11.0.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 891 kB/s 
Collecting sqlalchemy>=1.3
  Downloading SQLAlchemy-1.3.13.tar.gz (6.0 MB)
     |████████████████████████████████| 6.0 MB 4.2 MB/s 
Collecting numpy>=1.16
  Downloading numpy-1.18.1-cp37-cp37m-macosx_10_9_x86_64.whl (15.1 MB)
     |████████████████████████████████| 15.1 MB 2.9 MB/s 
Collecting pandas>=0.24
  Downloading pandas-1.0.1-cp37-cp37m-macosx_10_9_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 27.4 MB/s 
Collecting pyarrow<0.14,>=0.12.0
  Downloading pyarrow-0.13.0-cp37-cp37m-macosx_10_6_intel.whl (29.1 MB)
     |████████████████████████████████| 29.1 MB 10.5 MB/s 
Collecting packaging>=19.0
  Downloading packaging-20.1-py2.py3-none-any.whl (36 kB)
Collecting rbc-project
  Downloading rbc_project-0.2.0.dev0-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 10.0 MB/s 
Collecting six>=1.7.2
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting pytz>=2017.2
  Downloading pytz-2019.3-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 20.1 MB/s 
Collecting python-dateutil>=2.6.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 19.8 MB/s 
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 7.7 MB/s 
Collecting numba
  Downloading numba-0.48.0-cp37-cp37m-macosx_10_9_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 14.1 MB/s 
Collecting llvmlite>=0.29
  Downloading llvmlite-0.31.0-cp37-cp37m-macosx_10_9_x86_64.whl (15.9 MB)
     |████████████████████████████████| 15.9 MB 22.5 MB/s 
Collecting netifaces
  Downloading netifaces-0.10.9-cp37-cp37m-macosx_10_14_x86_64.whl (12 kB)
Collecting thriftpy2
  Downloading thriftpy2-0.4.10.tar.gz (301 kB)
     |████████████████████████████████| 301 kB 20.6 MB/s 
Collecting tblib
  Downloading tblib-1.6.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in /Users/randyzwitch/pymapdvenv/lib/python3.7/site-packages (from numba->rbc-project->pymapd) (45.2.0)
Collecting ply<4.0,>=3.4
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 14.2 MB/s 
Building wheels for collected packages: pymapd, thrift, sqlalchemy, thriftpy2
  Building wheel for pymapd (setup.py) ... done
  Created wheel for pymapd: filename=pymapd-0.19.0-py3-none-any.whl size=105382 sha256=0026b0c6a3bbe45b94fece7a2210489eda8a5f9078b5a92f5f7b4a4d44308368
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/5a/c9/6e/469d7cd6015547a2ef1d2b67263da7ef07d377e86726eeed49
  Building wheel for thrift (setup.py) ... done
  Created wheel for thrift: filename=thrift-0.11.0-py3-none-any.whl size=136034 sha256=55b14a68e501a217f854c5f26257461ca686a05130c23cf0e54f39ee4af4b043
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/4c/14/51/0a5ef9b177fce063cbb528b80a24e672ca356f7b09a3a137f3
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.13-cp37-cp37m-macosx_10_7_x86_64.whl size=1171714 sha256=f85b20660f704c44ecf4d200517053af7d488941a887fb461fc2912a932710af
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/b9/ba/77/163f10f14bd489351530603e750c195b0ceceed2f3be2b32f1
  Building wheel for thriftpy2 (setup.py) ... done
  Created wheel for thriftpy2: filename=thriftpy2-0.4.10-cp37-cp37m-macosx_10_7_x86_64.whl size=476559 sha256=4a55a721d9430d54759664bfbffcdd36fb1f306efc14ad94d9ab4efc52114744
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/ad/5c/07/4c15a45cc1147d3ff9c8d006b783b665c2e34ecc6bd7286bd0
Successfully built pymapd thrift sqlalchemy thriftpy2
Installing collected packages: six, thrift, sqlalchemy, numpy, pytz, python-dateutil, pandas, pyarrow, pyparsing, packaging, llvmlite, numba, netifaces, ply, thriftpy2, tblib, rbc-project, pymapd
Successfully installed llvmlite-0.31.0 netifaces-0.10.9 numba-0.48.0 numpy-1.18.1 packaging-20.1 pandas-1.0.1 ply-3.11 pyarrow-0.13.0 pymapd-0.19.0 pyparsing-2.4.6 python-dateutil-2.8.1 pytz-2019.3 rbc-project-0.2.0.dev0 six-1.14.0 sqlalchemy-1.3.13 tblib-1.6.0 thrift-0.11.0 thriftpy2-0.4.10
(pymapdvenv) Randys-MBP:bin randyzwitch$ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymapd
>>> 
```

**Comment by randyzwitch** [comment]
Not sure what to think of this, seems to work with 3.6.8 as well:

```python
Randys-MBP:~ randyzwitch$ cd pymapdvenv36/
Randys-MBP:pymapdvenv36 randyzwitch$ virtualenv -p python3.6 .
created virtual environment in 460ms CPython3Posix(dest=/Users/randyzwitch/pymapdvenv36, clear=False, global=False) with seeder FromAppData pip=latest setuptools=latest wheel=latest 

(pymapdvenv36) Randys-MBP:bin randyzwitch$ pip install pymapd
Collecting pymapd
  Using cached pymapd-0.19.0.tar.gz (6.4 MB)
Collecting thrift==0.11.0
  Using cached thrift-0.11.0.tar.gz (52 kB)
Collecting sqlalchemy>=1.3
  Using cached SQLAlchemy-1.3.13.tar.gz (6.0 MB)
Collecting numpy>=1.16
  Downloading numpy-1.18.1-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
     |████████████████████████████████| 15.2 MB 1.9 MB/s 
Collecting pandas>=0.24
  Downloading pandas-1.0.1-cp36-cp36m-macosx_10_9_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 31.9 MB/s 
Collecting pyarrow<0.14,>=0.12.0
  Downloading pyarrow-0.13.0-cp36-cp36m-macosx_10_6_intel.whl (29.1 MB)
     |████████████████████████████████| 29.1 MB 372 kB/s 
Collecting packaging>=19.0
  Using cached packaging-20.1-py2.py3-none-any.whl (36 kB)
Collecting rbc-project
  Using cached rbc_project-0.2.0.dev0-py3-none-any.whl (71 kB)
Collecting six>=1.7.2
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting pytz>=2017.2
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting python-dateutil>=2.6.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
Collecting numba
  Downloading numba-0.48.0-cp36-cp36m-macosx_10_9_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 1.3 MB/s 
Collecting thriftpy2
  Using cached thriftpy2-0.4.10.tar.gz (301 kB)
Collecting netifaces
  Downloading netifaces-0.10.9-cp36-cp36m-macosx_10_13_x86_64.whl (12 kB)
Collecting tblib
  Using cached tblib-1.6.0-py2.py3-none-any.whl (12 kB)
Collecting llvmlite>=0.29
  Downloading llvmlite-0.31.0-cp36-cp36m-macosx_10_9_x86_64.whl (15.9 MB)
     |████████████████████████████████| 15.9 MB 10.2 MB/s 
Requirement already satisfied: setuptools in /Users/randyzwitch/pymapdvenv36/lib/python3.6/site-packages (from numba->rbc-project->pymapd) (45.2.0)
Collecting ply<4.0,>=3.4
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Building wheels for collected packages: pymapd, thrift, sqlalchemy, thriftpy2
  Building wheel for pymapd (setup.py) ... done
  Created wheel for pymapd: filename=pymapd-0.19.0-py3-none-any.whl size=105382 sha256=a2b4984318a61279b0d7e03f0f074b4ecb0ca5fb5777eb73b68667d959fbeff5
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/a1/1c/c3/a47621d8b9d0c1d1d3278a2b6e34edf5990419dd207b0ae30b
  Building wheel for thrift (setup.py) ... done
  Created wheel for thrift: filename=thrift-0.11.0-cp36-cp36m-macosx_10_9_x86_64.whl size=156208 sha256=a1fea31528154065222a3fd75706b00870092cc272fcd7fad5785f7e4bf05acc
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/69/de/a0/2d866930ccd93ad7cfbe660dc7368ee4317f0e98edc7e062c0
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.13-cp36-cp36m-macosx_10_9_x86_64.whl size=1171166 sha256=84f095fc6ad8c863cd688e4b6511e0b643f291a38014948206ea82676257282d
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/28/3e/f9/8eca04781258bb6956ffba37e4e6e6951e5b3a16d4494b91cb
  Building wheel for thriftpy2 (setup.py) ... done
  Created wheel for thriftpy2: filename=thriftpy2-0.4.10-cp36-cp36m-macosx_10_9_x86_64.whl size=476098 sha256=338baf3a53cdeab7883db7bbd7bd7f4ecd01b36f7efd350ff2da08a06c7c0252
  Stored in directory: /Users/randyzwitch/Library/Caches/pip/wheels/ec/53/cd/18e71779aaa6da996f434f00fb716b13b5b36d230a7ab94e0e
Successfully built pymapd thrift sqlalchemy thriftpy2
Installing collected packages: six, thrift, sqlalchemy, numpy, pytz, python-dateutil, pandas, pyarrow, pyparsing, packaging, llvmlite, numba, ply, thriftpy2, netifaces, tblib, rbc-project, pymapd
Successfully installed llvmlite-0.31.0 netifaces-0.10.9 numba-0.48.0 numpy-1.18.1 packaging-20.1 pandas-1.0.1 ply-3.11 pyarrow-0.13.0 pymapd-0.19.0 pyparsing-2.4.6 python-dateutil-2.8.1 pytz-2019.3 rbc-project-0.2.0.dev0 six-1.14.0 sqlalchemy-1.3.13 tblib-1.6.0 thrift-0.11.0 thriftpy2-0.4.10
(pymapdvenv36) Randys-MBP:bin randyzwitch$ python
Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymapd
>>> pymapd.__version__
'0.19.0'
```

**Comment by randyzwitch** [comment]
```python
(pymapdvenv36) Randys-MBP:bin randyzwitch$ pip freeze
llvmlite==0.31.0
netifaces==0.10.9
numba==0.48.0
numpy==1.18.1
packaging==20.1
pandas==1.0.1
ply==3.11
pyarrow==0.13.0
pymapd==0.19.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
rbc-project==0.2.0.dev0
six==1.14.0
SQLAlchemy==1.3.13
tblib==1.6.0
thrift==0.11.0
thriftpy2==0.4.10
```

**Comment by randyzwitch** [comment]
The only difference I can see between my environment and yours is `packaging==20.1` (besides the extra packages you've installed). I would've assumed that got installed automatically as it did for me.

**Comment by BrianLondon** [comment]
Well, I got it working. Using the output of your `pip freeze` didn't fix it but swapping virtualenv tooling might have.  Here's the output that worked:

```
➜  tmp virtualenv -p python3.6 .
Running virtualenv with interpreter /opt/local/bin/python3.6
Already using interpreter /opt/local/bin/python3.6
Using base prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/brianlondon/Documents/consulting/tamr/example-exports/omnisci/project/tmp/bin/python3.6
Also creating executable in /Users/brianlondon/Documents/consulting/tamr/example-exports/omnisci/project/tmp/bin/python
Installing setuptools, pip, wheel...
done.
➜  tmp source bin/activate
(tmp) ➜  tmp pip install pymapd
Processing /Users/brianlondon/Library/Caches/pip/wheels/a1/1c/c3/a47621d8b9d0c1d1d3278a2b6e34edf5990419dd207b0ae30b/pymapd-0.19.0-py3-none-any.whl
Processing /Users/brianlondon/Library/Caches/pip/wheels/28/3e/f9/8eca04781258bb6956ffba37e4e6e6951e5b3a16d4494b91cb/SQLAlchemy-1.3.13-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting pyarrow<0.14,>=0.12.0
  Using cached pyarrow-0.13.0-cp36-cp36m-macosx_10_6_intel.whl (29.1 MB)
Processing /Users/brianlondon/Library/Caches/pip/wheels/69/de/a0/2d866930ccd93ad7cfbe660dc7368ee4317f0e98edc7e062c0/thrift-0.11.0-py3-none-any.whl
Collecting packaging>=19.0
  Using cached packaging-20.1-py2.py3-none-any.whl (36 kB)
Collecting numpy>=1.16
  Using cached numpy-1.18.1-cp36-cp36m-macosx_10_9_x86_64.whl (15.2 MB)
Collecting rbc-project
  Using cached rbc_project-0.2.0.dev0-py3-none-any.whl (71 kB)
Collecting pandas>=0.24
  Using cached pandas-1.0.1-cp36-cp36m-macosx_10_9_x86_64.whl (9.9 MB)
Collecting six>=1.0.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
Collecting numba
  Using cached numba-0.48.0-cp36-cp36m-macosx_10_9_x86_64.whl (2.0 MB)
Collecting netifaces
  Using cached netifaces-0.10.9-cp36-cp36m-macosx_10_13_x86_64.whl (12 kB)
Processing /Users/brianlondon/Library/Caches/pip/wheels/ec/53/cd/18e71779aaa6da996f434f00fb716b13b5b36d230a7ab94e0e/thriftpy2-0.4.10-cp36-cp36m-macosx_10_9_x86_64.whl
Collecting tblib
  Using cached tblib-1.6.0-py2.py3-none-any.whl (12 kB)
Collecting llvmlite>=0.29
  Using cached llvmlite-0.31.0-cp36-cp36m-macosx_10_9_x86_64.whl (15.9 MB)
Collecting python-dateutil>=2.6.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.2
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Requirement already satisfied: setuptools in ./lib/python3.6/site-packages (from numba->rbc-project->pymapd) (45.2.0)
Collecting ply<4.0,>=3.4
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Installing collected packages: sqlalchemy, numpy, six, pyarrow, thrift, pyparsing, packaging, llvmlite, numba, netifaces, ply, thriftpy2, tblib, rbc-project, python-dateutil, pytz, pandas, pymapd
Successfully installed llvmlite-0.31.0 netifaces-0.10.9 numba-0.48.0 numpy-1.18.1 packaging-20.1 pandas-1.0.1 ply-3.11 pyarrow-0.13.0 pymapd-0.19.0 pyparsing-2.4.6 python-dateutil-2.8.1 pytz-2019.3 rbc-project-0.2.0.dev0 six-1.14.0 sqlalchemy-1.3.13 tblib-1.6.0 thrift-0.11.0 thriftpy2-0.4.10
(tmp) ➜  tmp python
Python 3.6.10 (default, Dec 21 2019, 11:39:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymapd
>>> pymapd.__version__
'0.19.0'
>>>
```

In this case I did a `virtualenv -p python3.6 .` like you did rather than `mkvirtualenv tmp` like last time. This installed 3.6.10 instead of 3.6.8.

Since I'm working now I can close this, but since I don't think we identified the issue I'm happy to help you keep trouble shooting my original environment.

**Comment by BrianLondon** [comment]
Alright, I figured it out and was 100% my fault. I had a wonky python path setting such that a file `myapp/databases/omnisci.py` was getting loaded as `omnisci` rather than `myapp.databases.omnisci` and shadowing the library.

Sorry for the confusion, and thank you @randyzwitch for the help.
