### ISSUE TITLE
Hangs in 'COPY <table> FROM...'

### ISSUE THREAD

**Issue by tcourregesJC** [omnisci/pymapd#56]
Hi!

I'm creating a daily job that moves data from another database into MapD, it generates a .csv file that is moved into MapD server and then use pymapd (execute) to launch the "copy <table> from '<.csv>'" statement. The problem is that when the .csv is large enough, it hangs and never returns. Any idea how to prevent this?

`>>> copy_response = list(mapd.execute("COPY FACT_USER_ACQUISITION_DAILY_MAPD FROM '/raidStorage/imports/FACT_USER_ACQUISITION_DAILY_MAPD_FINAL.csv';"))[0][0]`

`^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/pymapd/connection.py", line 226, in execute
    return c.execute(operation, parameters=parameters)
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/pymapd/cursor.py", line 120, in execute
    nonce=None, first_n=-1)
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/mapd/MapD.py", line 1030, in sql_execute
    return self.recv_sql_execute()
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/mapd/MapD.py", line 1046, in recv_sql_execute
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 60, in readAll
    chunk = self.read(sz - have)
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/thrift/transport/TTransport.py", line 161, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
  File "/home/user/.conda/envs/teradata_env/lib/python3.5/site-packages/thrift/transport/TSocket.py", line 117, in read
    buff = self.handle.recv(sz)
KeyboardInterrupt
`

**Comment by andrewseidl** [comment]
Hi @tcourregesJC ,

Do your `COPY FROM` commands succeed when run from the `mapdql` command line client, or do they also hang there? That will help us determine if it's a `pymapd` issue or if it's a `mapd-core` issue.

1. How large are the input files which succeed and fail? # rows, # columns, file size

2. Does it seem like it's time-based, ie does it seem to fail after 30 seconds or similar?

3. Do the imports otherwise seem to succeed? Is the number of rows added the same as the number of rows in the file (possibly minus one for the header).

4. If the number of rows is different, could you provide your `mapd_server*INFO*` logs? They're usually located under `/var/lib/mapd/data/mapd_log` or `/raidStorage/mapd-storage/data/mapd_log` or similar.

5. Are you aware of our Java-based `SQLImporter` tool? It allows you to move data from other databases into MapD via JDBC. Might eliminate the need to write out to a CSV depending on your use case. https://www.mapd.com/docs/latest/mapd-core-guide/loading-data/#sql-importer

**Comment by tcourregesJC** [comment]
Hi @andrewseidl, the data is loaded successfuly.

1. The file i'm trying now is 24GB, 21944274 rows and 158 columns.
2. Yes, I think it's time based, I've tried with smaller csv files and it works fine.
3. Yes, the number of rows matches the rows in the csv and in the other database.
4. The number of rows match.
5. Yes! I know it's possible to move data via JDBC but it's considerablyslower than moving the file to the server and using "copy xxxx from .csv"

Thanks! Let me know if you need more info

**Comment by randyzwitch** [comment]
I'm going to close this issue, if only because so many changes have come through MapD/OmniSci in the last year. If this is still an issue, please let us know and we can re-open the issue/create a new one
